config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'drawers/index'
  root to: "partitions#index"
  resources :users, only: [:edit, :update]
  resources :partitions, only: [:new, :create, :destroy, :show] do
    resources :drawers, only: :index
    collection do
      get 'search'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drawer.rb
class Drawer < ApplicationRecord
  belongs_to :user
  belongs_to :partition
  has_many_attached :images
end

app/models/partition.rb
class Partition < ApplicationRecord
  belongs_to :user
  has_many :drawers
  has_many_attached :images

  def self.search(search)
    if search != ""
      Partition.where('text LIKE(?)', "%#{search}%")
    else
      Partition.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :drawers
  has_many :partitions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/drawers_controller.rb
class DrawersController < ApplicationController
  before_action :set_drawer, only: [:destroy, :update, :edit, :show]
  before_action :move_to_new_user_session
 # before_action :set_partition

  def index
    @partition = Partition.find(params[:id])
  end

  private

  #  def set_partition
  #    @partitions = Partition.find(params[:id])
  #  end

  def move_to_new_user_session
    redirect_to new_user_session_path unless user_signed_in?
  end

end

app/controllers/partitions_controller.rb
class PartitionsController < ApplicationController

  before_action :search_product

  def index
    @users = User.all
    @partitions = Partition.all.order('created_at DESC')
    set_user_column
    set_created_at_column
  end

  def new
    @partition = Partition.new
  end

  def create
    @partition = Partition.new(partition_params)
    if @partition.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    partition = Partition.find(params[:id])
    partition.destroy
    redirect_to root_path
  end

  def show
    @partitions = Partition.all
    @partition = Partition.find(params[:id])
    @results = @p.result.includes(:user)
    set_user_column
    set_created_at_column
  end

  def search
    #@partitions = Partition.search(params[:keyword])
    @partitions = Partition.all
    #@partition = Partition.find(params[:id])
    @results = @p.result.includes(:user)
    set_user_column
    set_created_at_column

  end

  private

  def partition_params
    params.require(:partition).permit(:title, :category, :comment, images: [], user_ids: []).merge(user_id: current_user.id)
  end

  def search_product
    @p = Partition.ransack(params[:q])  # 検索オブジェクトを生成
  end

  def set_user_column
    @user_name = User.select("name").distinct
  end

  def set_created_at_column
    @partition_created_at = Partition.select("created_at").distinct
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawers_helper.rb
module DrawersHelper
end

app/helpers/partitions_helper.rb
module PartitionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drawers/#new.html.erb
<div class='chat-room-form'>
  <h1>新しい引き出し</h1>
  <%=form_with model: @drawer, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :タイトル, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :title, class: 'chat__room_name chat-room-form__input', placeholder: 'タイトルを入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :カテゴリー, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :category, class: 'chat__room_name chat-room-form__input', placeholder: 'カテゴリーを入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像1, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'drawer[images][]', id: 'drawer_image' %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像2, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'drawer[images][]', id: 'drawer_image' %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像3, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'drawer[images][]', id: 'drawer_image' %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像4, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'drawer[images][]', id: 'drawer_image' %>
      </div>
    </div>
     <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :コメント, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :comment, class: 'chat__room_name chat-comment-form__input', placeholder: 'コメントを入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/drawers/_drawer.html.erb
<div class="drawer">
  <% @partition.images.each do |image| %>
    <%= image_tag image.variant(resize:'250x250'), class: 'message-image' %>
  <% end %>
</div>

app/views/drawers/_main_drawer.html.erb
<div class="drawer-header">
   <div class="left-header">
    <div class="header-title">
      <%= @partition.title %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <a href="#">編集</a>
    </div>
    <div class="header-button">
      <%= link_to "削除", partition_path(@partition), method: :delete %>
    </div>
  </div>
</div>

<div class="main-drawer">
  <%= render partial: 'drawer' %>
</div>

<div class="form">
  <div class="form-comment-up">
    <div class='form-comment'>
      <%= @partition.comment %>
    </div>
  </div>
</div>

app/views/drawers/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to edit_user_path(current_user) do %>
      <%= current_user.name %>
    <% end %>
  </div>
  <div class="create-drawer">
      <%= link_to "新しい引き出しを作る", new_partition_path %>
  </div>
</div>

<%= form_with(url: root_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class="drawers">
  <% @partitions.each do |partition| %>
    <div class="side-drawer">
      <div class="drawer-title">
        <%= link_to partition.title, partition_drawers_path(partition.id) %>
        <div class="message-date">
          <%= l partition.created_at %>
        </div>
      </div>
    </div>
   <% end %>
</div>

app/views/drawers/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="drawer">
    <%= render "main_drawer" %>
  </div>
</div>

app/views/drawers/new.html.erb
<div class='chat-room-form'>
  <h1>新しい引き出し</h1>
  <%=form_with model: @drawer, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :タイトル, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :title, class: 'chat__room_name chat-room-form__input', placeholder: 'タイトルを入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :カテゴリー, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :category, class: 'chat__room_name chat-room-form__input', placeholder: 'カテゴリーを入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像1, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'drawer[images][]', id: 'drawer_image' %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像2, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'drawer[images][]', id: 'drawer_image' %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像3, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'drawer[images][]', id: 'drawer_image' %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像4, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'drawer[images][]', id: 'drawer_image' %>
      </div>
    </div>
     <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :コメント, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :comment, class: 'chat__room_name chat-comment-form__input', placeholder: 'コメントを入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrawerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partitions/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to edit_user_path(current_user) do %>
      <%= current_user.name %>
    <% end %>
  </div>
  <div class="create-drawer">
      <%= link_to "新しい引き出しを作る", new_partition_path %>
  </div>
</div>

<div class="side-bar-search">
  <%= search_form_for @p, url: search_partitions_path do |f| %>
    <div class="search-list">
    <%= f.label :user_name_eq, '店名:' %>
      <%= f.collection_select :user_name_eq, @user_name, :name, :name,  include_blank: '指定なし' %>
    <%= f.submit '検索' %>
    </div>
  <% end %>
  <%= search_form_for @p, url: search_partitions_path do |f| %>
    <div class="search-list">
    <%= f.label :created_at_eq, '日時:' %>
      <%= f.collection_select :created_at_eq, @partition_created_at, :created_at, :created_at, include_blank: '指定なし' %>
    <%= f.submit '検索' %>
    </div>
  <% end %>
</div>

<div class="drawers">
  <% @partitions.each do |partition| %>
    <div class="side-drawer">
      <div class="drawer-title">
        <%= link_to partition.title, partition_path(partition) %>
        <div class="message-date">
          <%= l partition.created_at %>
        </div>
      </div>
    </div>
   <% end %>
</div>

app/views/partitions/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "side_bar" %>
  </div>
</div>

app/views/partitions/new.html.erb
<div class='chat-room-form'>
  <h1>新しい引き出し</h1>
  <%=form_with model: @partition, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :タイトル, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :title, class: 'chat__room_name chat-room-form__input', placeholder: 'タイトルを入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :作成日時, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :category, class: 'chat__room_name chat-room-form__input', placeholder: '半角数字で"2020/10"のように入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像1, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'partition[images][]', id: 'partition_image' %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像2, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'partition[images][]', id: 'partition_image' %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像3, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'partition[images][]', id: 'partition_image' %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :画像4, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.file_field :image, name: 'partition[images][]', id: 'partition_image' %>
      </div>
    </div>
     <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :コメント, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :comment, class: 'chat__room_name chat-comment-form__input', placeholder: 'コメントを入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/partitions/search.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <div class="side-bar-header">
      <div class="header-name">
        <%= link_to edit_user_path(current_user) do %>
          <%= current_user.name %>
        <% end %>
      </div>
      <div class="create-drawer">
          <%= link_to "新しい引き出しを作る", new_partition_path %>
      </div>
    </div>

    <div class="side-bar-search">
      <%= search_form_for @p, url: search_partitions_path do |f| %>
        <div class="search-list">
        <%= f.label :user_name_eq, '店名:' %>
          <%= f.collection_select :user_name_eq, @user_name, :name, :name,  include_blank: '指定なし' %>
        <%= f.submit '検索' %>
        </div>
      <% end %>
      <%= search_form_for @p, url: search_partitions_path do |f| %>
        <div class="search-list">
        <%= f.label :created_at_eq, '日時:' %>
          <%= f.collection_select :created_at_eq, @partition_created_at, :created_at, :created_at, include_blank: '指定なし' %>
        <%= f.submit '検索' %>
        </div>
      <% end %>
    </div>

    <div class="drawers">
      <% @results.each do |result| %>
        <div class="side-drawer">
          <div class="drawer-title">
            <%= link_to result.title, partition_path(@partitions.ids) %>
            <div class="message-date">
              <%= l result.created_at %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/partitions/show.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "side_bar" %>
  </div>

  <div class="drawer">
    <div class="drawer-header">
      <div class="left-header">
        <div class="header-title">
          <%= "★店名：" %>
          <%= @partition.user.name %>
        </div>
        <div class="header-title">
          <%= "★タイトル：" %>
          <%= @partition.title %>
        </div>
        <div class="header-title">
          <%= "作成日：" %>
          <%= l @partition.created_at %>
        </div>
      </div>
      <% if user_signed_in? && current_user.id == @partition.user_id %>
      <div class="right-header">
        <div class="header-button">
          <%= link_to "削除", partition_path(@partition), method: :delete %>
        </div>
      </div>
      <% end %>
    </div>

    <div class="main-drawer">
      <%#= render partial: 'drawers/drawer' %>
      <div class="drawer">
        <div class="grid">
          <% @partition.images.each do |image| %>
            <%= image_tag image.variant(resize:'250x250'), class: 'message-image' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="form">
      <div class="form-comment-up">
        <div class='form-comment'>
          <%= @partition.comment %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "引き出しに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>